### ISSUE TITLE
The plugin is not activated when installing it from Catalog Display Module

### ISSUE THREAD

**Issue by fobos235** [overvis/opencart-plugins#13]
The plugin is not activated when installing it from Catalog Display Module, I have already repeated the steps several times and it is not installed in my opencart v.3.0.3.2. I'd appreciate your help.

**Comment by qwerty541** [comment]
Can't understand what means yours "installing it from Catalog Display Module". There are only two ways to install plugins: using .ocmod.zip file from admin panel and by hand through ftp client. Installation of this plugin is only available through admin panel. If the installation went in any other way, then most likely the plugin is not installed correctly, respectively, it does not work. If the plugin is installed correctly, check if the installed version of PHP matches the one specified in the requirements + if the same problem occur when installing other plugins.

**Comment by qwerty541** [comment]
Just installed all the plugins in this repository on a clean locally installed OpenCart with the same version that you have. There were no problems during installation, so most likely your problem is not in my code. I can assume that you forgot to reload the plugin cache after installation.

**Comment by qwerty541** [comment]
Is your issue resolved? Can i close it?

**Comment by mitrecyclers** [comment]
I have the same issue. Installed and I can it in installed packages. On modification. Pressed refresh many times but it is not showing in

Extensions —> modules so no way to enable/ configure it. Using PHP7.3 and OC 3.x.x

Any help?

**Comment by qwerty541** [comment]
> I have the same issue. Installed and I can it in installed packages. On modification. Pressed refresh many times but it is not showing in
> 
> Extensions —> modules so no way to enable/ configure it. Using PHP7.3 and OC 3.x.x
> 
> Any help?

Try removing the semicolon before these lines in php.ini

```
;display_errors = 1
;error_reporting = E_ALL
```

After that, try installing the plugin again and see if it shows any errors + check the error logs. If nothing shows, I don’t even know how to help you. As I wrote above, I recently tested the work of all plugins in this repository on a clean OpenCart v3.0.3.2 and PHP v7.2 and everything worked without problems.

**Comment by mhcwebdesign** [comment]
The solution is simple: I managed to reproduce the same error. You need to properly zip up your files, otherwise you won't be able to install them on a Linux system! E.g. at the moment you got a list of long flat file names like:
```
Simple-cookie-policy-notice.ocmod/upload\catalog\view\theme\default\template\extension\module\cookie_notice.twig
Simple-cookie-policy-notice.ocmod/README.md
Simple-cookie-policy-notice.ocmod/LICENSE
Simple-cookie-policy-notice.ocmod/install.xml
Simple-cookie-policy-notice.ocmod/upload\catalog\controller\extension\module\cookie_notice.php
Simple-cookie-policy-notice.ocmod/upload\admin\view\template\extension\module\cookie_notice.twig
Simple-cookie-policy-notice.ocmod/upload\admin\controller\extension\module\cookie_notice.php
Simple-cookie-policy-notice.ocmod/upload\catalog\language\en-gb\extension\module\cookie_notice.php
Simple-cookie-policy-notice.ocmod/upload\admin\language\en-gb\extension\module\cookie_notice.php
```
but not a proper folder structure, hence the OpenCart installer won't see the **upload** folder because it doesn't exist in your list.

**Comment by svendaems** [comment]
Thanks @mhcwebdesign for the tip.
I had the same issue, uploaded the ocmod.zip via the installer but module wasn't showed.
Uploaded then the folders manually & now it's visible.

Another issue I found:
in install.xml, you search for `<input type="text" name="sort_order" value="{{ sort_order }}" placeholder="{{ entry_sort_order }}" id="input-sort-order" class="form-control"/>`, this cannot be found.
It should be `<input type="text" name="sort_order" value="{{ sort_order }}" placeholder="{{ entry_sort_order }}" id="input-sort-order" class="form-control" />` (see extra space in the end).

**Comment by qwerty541** [comment]
> The solution is simple: I managed to reproduce the same error. You need to properly zip up your files, otherwise you won't be able to install them on a Linux system! E.g. at the moment you got a list of long flat file names like:
> 
> ```
> Simple-cookie-policy-notice.ocmod/upload\catalog\view\theme\default\template\extension\module\cookie_notice.twig
> Simple-cookie-policy-notice.ocmod/README.md
> Simple-cookie-policy-notice.ocmod/LICENSE
> Simple-cookie-policy-notice.ocmod/install.xml
> Simple-cookie-policy-notice.ocmod/upload\catalog\controller\extension\module\cookie_notice.php
> Simple-cookie-policy-notice.ocmod/upload\admin\view\template\extension\module\cookie_notice.twig
> Simple-cookie-policy-notice.ocmod/upload\admin\controller\extension\module\cookie_notice.php
> Simple-cookie-policy-notice.ocmod/upload\catalog\language\en-gb\extension\module\cookie_notice.php
> Simple-cookie-policy-notice.ocmod/upload\admin\language\en-gb\extension\module\cookie_notice.php
> ```
> 
> but not a proper folder structure, hence the OpenCart installer won't see the **upload** folder because it doesn't exist in your list.

Thank you for help, i updated script for assembling plugins into zip archives and reassembled all plugins in last commit. Can you check please if this error happens now?

**Comment by qwerty541** [comment]
> Thanks @mhcwebdesign for the tip.
> I had the same issue, uploaded the ocmod.zip via the installer but module wasn't showed.
> Uploaded then the folders manually & now it's visible.
> 
> Another issue I found:
> in install.xml, you search for `<input type="text" name="sort_order" value="{{ sort_order }}" placeholder="{{ entry_sort_order }}" id="input-sort-order" class="form-control"/>`, this cannot be found.
> It should be `<input type="text" name="sort_order" value="{{ sort_order }}" placeholder="{{ entry_sort_order }}" id="input-sort-order" class="form-control" />` (see extra space in the end).

Check this file in the official Opencart repository:

https://github.com/opencart/opencart/blob/master/upload/admin/view/template/catalog/product_form.twig#L758

and try there find with `Ctrl + F` your variant first and then mine. Everything is correct at the moment.

**Comment by mhcwebdesign** [comment]
> Thank you for help, i updated script for assembling plugins into zip archives and reassembled all plugins in last commit. Can you check please if this error happens now?

The zip-archive is still broken when downloaded from the OpenCart marketplace, it contains no folders structure.

**Comment by qwerty541** [comment]
> > Thank you for help, i updated script for assembling plugins into zip archives and reassembled all plugins in last commit. Can you check please if this error happens now?
> 
> The zip-archive is still broken when downloaded from the OpenCart marketplace, it contains no folders structure.
Currently I have updated it only on github repo to check if my fix works. If you confirm that error fixed i will upload it on OpenCart marketplace.

**Comment by qwerty541** [comment]
Currently I have updated it only on github repository to check if my fix works. If you confirm that error fixed i will upload it on OpenCart marketplace.

**Comment by qwerty541** [comment]
> > Thank you for help, i updated script for assembling plugins into zip archives and reassembled all plugins in last commit. Can you check please if this error happens now?
> 
> The zip-archive is still broken when downloaded from the OpenCart marketplace, it contains no folders structure.

Currently I have updated it only on github repository to check if my fix works. If you confirm that error fixed i will upload it on OpenCart marketplace.

**Comment by mhcwebdesign** [comment]
It's still broken on github, too! 

E.g. the file 
'opencart-plugins/Simple-cookie-policy-notice/Simple-cookie-policy-notice.ocmod.zip' 
has loads of top-level folders only whose names contain '\\' characters, e.g. 
'upload\admin\language\en-gb\extension\module', 

and top-level only files whose names contain '\\' characters, e.g. 
'upload\admin\language\en-gb\extension\module\cookie_notice.php'. 

There is no proper folder structure. It looks like you are using a Windows script which doesn't know about Unix-style '/' path separators. Just use a proper ZIP utility, such as Winzip.

**Comment by qwerty541** [comment]
> It's still broken on github, too!
> 
> E.g. the file
> 'opencart-plugins/Simple-cookie-policy-notice/Simple-cookie-policy-notice.ocmod.zip'
> has loads of top-level folders only whose names contain '\' characters, e.g.
> 'upload\admin\language\en-gb\extension\module',
> 
> and top-level only files whose names contain '\' characters, e.g.
> 'upload\admin\language\en-gb\extension\module\cookie_notice.php'.
> 
> There is no proper folder structure. It looks like you are using a Windows script which doesn't know about Unix-style '/' path separators. Just use a proper ZIP utility, such as Winzip.

Is that folders structure correct?

```bash
$ zipinfo Catalog-display/Catalog-display.ocmod.zip
Archive:  Catalog-display/Catalog-display.ocmod.zip
Zip file size: 19854 bytes, number of entries: 41
-rw-rw-rw-  6.3 unx    12276 b- defX 20-Apr-11 19:59 Catalog-display.ocmod.zip
-rw-rw-rw-  6.3 unx     3058 b- defX 19-Oct-14 21:27 install.xml
-rw-rw-rw-  6.3 unx     1921 b- defX 19-Nov-25 23:47 README.md
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/controller/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/controller/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/controller/extension/module/
-rw-rw-rw-  6.3 unx     3721 b- defX 19-Oct-13 19:48 upload/admin/controller/extension/module/catalog_display.php
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/language/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/language/en-gb/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/language/en-gb/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/language/en-gb/extension/module/
-rw-rw-rw-  6.3 unx      411 b- defX 19-Sep-07 23:21 upload/admin/language/en-gb/extension/module/catalog_display.php
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/view/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/view/template/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/view/template/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/admin/view/template/extension/module/
-rw-rw-rw-  6.3 unx     2795 b- defX 19-Oct-13 19:48 upload/admin/view/template/extension/module/catalog_display.twig
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/controller/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/controller/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/controller/extension/module/
-rw-rw-rw-  6.3 unx     3843 b- defX 19-Nov-07 23:23 upload/catalog/controller/extension/module/catalog_display.php
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/language/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/language/en-gb/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/language/en-gb/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/language/en-gb/extension/module/
-rw-rw-rw-  6.3 unx       61 b- defX 19-Sep-07 23:38 upload/catalog/language/en-gb/extension/module/catalog_display.php
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/model/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/model/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/model/extension/module/
-rw-rw-rw-  6.3 unx     1712 b- defX 19-Nov-07 23:23 upload/catalog/model/extension/module/catalog_display.php
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/theme/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/theme/default/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/theme/default/template/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/theme/default/template/extension/
drwxrwxrwx  6.3 unx        0 b- stor 20-Apr-11 20:13 upload/catalog/view/theme/default/template/extension/module/
-rw-rw-rw-  6.3 unx     4195 b- defX 19-Aug-09 17:58 upload/catalog/view/theme/default/template/extension/module/catalog_display.twig
-rw-rw-rw-  6.3 unx     1093 b- defX 19-Dec-01 19:38 LICENSE
41 files, 35086 bytes uncompressed, 13754 bytes compressed:  60.8%
```

**Comment by mhcwebdesign** [comment]
No, there is no nested folders structure. Instead it's a list of top-level folders with long names, where the names include backslash characters which on Linux isn't treated as a path separator!

**Comment by qwerty541** [comment]
> No, there is no nested folders structure. Instead it's a list of top-level folders with long names, where the names include backslash characters which on Linux isn't treated as a path separator!

Can you please provide me an example of correct folders structure? Otherwise, I will long try to figure out how to do it right.

**Comment by maddy-mad** [comment]
Hi @qwerty541 is this resolved? I tried installing it but unable to use it.

**Comment by qwerty541** [comment]
> Hi @qwerty541 is this resolved? I tried installing it but unable to use it.

Hi, @maddy-mad. Honestly, I don't know if that resolved. Before opening this issue archives had roughly the following structure:

```
install.xml
README.md
upload/admin\controller\extension\module\catalog_display.php
upload/admin\language\en-gb\extension\module\catalog_display.php
upload/admin\view\template\extension\module\catalog_display.twig
upload/catalog\controller\extension\module\catalog_display.php
upload/catalog\language\en-gb\extension\module\catalog_display.php
upload/catalog\model\extension\module\catalog_display.php
upload/catalog\view\theme\default\template\extension\module\catalog_display.twig
LICENSE
```

As far as I understood it was wrong and now I changed it:

```
install.xml
README.md
upload/
upload/admin/
upload/admin/controller/
upload/admin/controller/extension/
upload/admin/controller/extension/module/
upload/admin/controller/extension/module/catalog_display.php
upload/admin/language/
upload/admin/language/en-gb/
upload/admin/language/en-gb/extension/
upload/admin/language/en-gb/extension/module/
upload/admin/language/en-gb/extension/module/catalog_display.php
upload/admin/view/
upload/admin/view/template/
upload/admin/view/template/extension/
upload/admin/view/template/extension/module/
upload/admin/view/template/extension/module/catalog_display.twig
upload/catalog/
upload/catalog/controller/
upload/catalog/controller/extension/
upload/catalog/controller/extension/module/
upload/catalog/controller/extension/module/catalog_display.php
upload/catalog/language/
upload/catalog/language/en-gb/
upload/catalog/language/en-gb/extension/
upload/catalog/language/en-gb/extension/module/
upload/catalog/language/en-gb/extension/module/catalog_display.php
upload/catalog/model/
upload/catalog/model/extension/
upload/catalog/model/extension/module/
upload/catalog/model/extension/module/catalog_display.php
upload/catalog/view/
upload/catalog/view/theme/
upload/catalog/view/theme/default/
upload/catalog/view/theme/default/template/
upload/catalog/view/theme/default/template/extension/
upload/catalog/view/theme/default/template/extension/module/
upload/catalog/view/theme/default/template/extension/module/catalog_display.twig
LICENSE
```

I have tested this on operating systems Debian and Windows 10 and everything worked for me. I have no idea why the plugin still doesn't work for certain people.
